### ISSUE TITLE
Add feature for most used websites

### ISSUE THREAD

**Issue by biel-correa** [dailydotdev/.github#7]
This is my first day using daily and I just loved it, but I miss the shortcuts for the most accessed websites like [this](https://imgur.com/a/AyvMNyd), I thought on adding them [here](https://imgur.com/a/4XlvEbu). Since the site will be the homepage of many browser this might be a must have feature.

# Feature request:
* Create a bar on the left where the user can choose what links are going to show.
* The bar can also load the links that are most accessed.
* The user can edit the link, name and image(maybe) of the shortcut.

**Comment by biel-correa** [comment]
I just found where it is, but I can't control what icons will show up plus they don't have a name which can be confusing depending on the user

**Comment by idoshamun** [comment]
Hey! Sorry for the super late response. I wasn't expected to see issues here.
All issues should be created here:
https://github.com/dailydotdev/daily

We use Chrome's API to fetch these websites. It is not possible to control them.
